### ISSUE TITLE
Create the request bus button and setup page

### ISSUE THREAD

**Issue by ItsAdel** [ubclaunchpad/accessyouth-web#6]
Have a button on the home page on top of the map. For the MVP, when the button is clicked, go to a page with the download link for iphone.

**Comment by salaz1382** [comment]
Hi Adil. Bro this week is crazy for me, have 1 programming proficiency test and have to submit an important application. Do you mind taking charge of this..Thanks

**Comment by ItsAdel** [comment]
No worries :)
